CREATE TABLE COLABORADOR 
(
  NOME VARCHAR2(200) NOT NULL 
, CPF VARCHAR2(11) NOT NULL 
, CONSTRAINT COLABORADOR_PK PRIMARY KEY 
  (
    CPF 
  )
  ENABLE 
);

CREATE TABLE OPCAO 
(
  ID NUMBER NOT NULL 
, OPCAO VARCHAR2(200)
, CPF_COLABORADOR VARCHAR2(11) NOT NULL 
, CONSTRAINT CONTATO_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ADD CONSTRAINT OPCAO_COLABORADOR_FK FOREIGN KEY
(
  CPF_COLABORADOR
)
REFERENCES COLABORADOR
(
  CPF 
)
ENABLE;

CREATE SEQUENCE S_OPCAO INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1;


